spring:
  profiles:
    active: mysql

---

spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url: jdbc:h2:file:~/h2-database-generated-files/person
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
  liquibase:
    change-log: classpath:/src/test/resources/db/changelog/db.changelog-master.yaml
    enabled: false
  servlet:
    multipart:
      max-file-size: 15GB
      max-request-size: 15GB
  logging:
    level:
      root: WARN
      pl.kurs.ws_test3r: INFO
  async:
    executor:
      corePoolSize: 1
      maxPoolSize: 1
      queueCapacity: 0
      threadNamePrefix: importTaskExecutor

---

spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/people_diary?useSSL=false&serverTimezone=CET
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
  liquibase:
    change-log: classpath:/src/test/resources/db/changelog/db.changelog-master.yaml
    enabled: false
  servlet:
    multipart:
      max-file-size: 15GB
      max-request-size: 15GB
  async:
    executor:
      corePoolSize: 1
      maxPoolSize: 1
      queueCapacity: 0
      threadNamePrefix: importTaskExecutor-
